// This file is @generated by prost-build.
/// Request to create a new branch. The caller must supply a fully-resolved
/// ancestry stack (no `number == 0` tip resolution is performed for
/// BranchCreate). The caller also pre-generates the branch `id` so that
/// retries are idempotent — a duplicate `id` already in use returns
/// ALREADY_EXISTS.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchCreateRequest {
    /// Caller-pre-generated branch id (typically a UUIDv7). Re-issuing the
    /// same id on retry yields ALREADY_EXISTS rather than creating a
    /// duplicate; this gives the RPC end-to-end retry idempotency.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// Human-readable name for the new branch. Must not collide with any
    /// live branch (tombstoned names are free for reuse).
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Identity to attribute as the branch creator. If unset, the server
    /// uses the authenticated JWT identity. If set, the caller must have
    /// permission to attribute branches to other identities.
    #[prost(string, optional, tag = "3")]
    pub creator: ::core::option::Option<::prost::alloc::string::String>,
    /// Free-form caller-defined tag for grouping or filtering. Server
    /// stores verbatim; empty string allowed.
    #[prost(string, tag = "4")]
    pub category: ::prost::alloc::string::String,
    /// Ancestry chain — parent-first, root-last. stack\[0\] is the
    /// immediate parent the new branch is forked from. Every entry's
    /// revision_signature must resolve to a known revision on its
    /// branch_id.
    #[prost(message, repeated, tag = "5")]
    pub stack: ::prost::alloc::vec::Vec<crate::lore::model::v1::BranchPoint>,
}
impl ::prost::Name for BranchCreateRequest {
    const NAME: &'static str = "BranchCreateRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchCreateRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchCreateRequest".into()
    }
}
/// Response containing the newly-created branch record.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchCreateResponse {
    /// Full Branch record including server-assigned `created` timestamp
    /// and the preserved stack.
    #[prost(message, optional, tag = "1")]
    pub branch: ::core::option::Option<crate::lore::model::v1::Branch>,
}
impl ::prost::Name for BranchCreateResponse {
    const NAME: &'static str = "BranchCreateResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchCreateResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchCreateResponse".into()
    }
}
/// Request to tombstone a live branch by id. Names are not used here
/// because they may have been recycled after a prior delete.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchDeleteRequest {
    /// Branch id obtained from a prior BranchGet / BranchList.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchDeleteRequest {
    const NAME: &'static str = "BranchDeleteRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchDeleteRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchDeleteRequest".into()
    }
}
/// Response carrying the post-delete branch record. The record's name
/// field is preserved even though the name → id mapping has been
/// erased.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchDeleteResponse {
    /// Tombstoned branch record (deleted = true).
    #[prost(message, optional, tag = "1")]
    pub branch: ::core::option::Option<crate::lore::model::v1::Branch>,
}
impl ::prost::Name for BranchDeleteResponse {
    const NAME: &'static str = "BranchDeleteResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchDeleteResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchDeleteResponse".into()
    }
}
/// Request to look up a branch by id or by name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchGetRequest {
    /// Lookup mode.
    #[prost(oneof = "branch_get_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<branch_get_request::Query>,
}
/// Nested message and enum types in `BranchGetRequest`.
pub mod branch_get_request {
    /// Lookup mode.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// Lookup by branch id — returns the branch live or tombstoned.
        #[prost(bytes, tag = "1")]
        Id(::prost::bytes::Bytes),
        /// Lookup by branch name — returns the live branch with that name
        /// only. Tombstoned branches are not resolvable by name.
        #[prost(string, tag = "2")]
        Name(::prost::alloc::string::String),
    }
}
impl ::prost::Name for BranchGetRequest {
    const NAME: &'static str = "BranchGetRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchGetRequest".into()
    }
}
/// Response containing the resolved branch record.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchGetResponse {
    /// Branch record matching the lookup.
    #[prost(message, optional, tag = "1")]
    pub branch: ::core::option::Option<crate::lore::model::v1::Branch>,
}
impl ::prost::Name for BranchGetResponse {
    const NAME: &'static str = "BranchGetResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchGetResponse".into()
    }
}
/// Request to stream branches with optional filters.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchListRequest {
    /// If set, only branches whose `creator` field is an exact
    /// byte-for-byte case-sensitive match are emitted. If unset, no
    /// creator filter is applied.
    #[prost(string, optional, tag = "1")]
    pub creator: ::core::option::Option<::prost::alloc::string::String>,
    /// If true, tombstoned branches are emitted with `Branch.deleted =  true`. Default false (only live branches emitted).
    #[prost(bool, tag = "2")]
    pub include_deleted: bool,
}
impl ::prost::Name for BranchListRequest {
    const NAME: &'static str = "BranchListRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchListRequest".into()
    }
}
/// One-per-stream-message response carrying a single branch record.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BranchListResponse {
    /// A branch matching the request's filters.
    #[prost(message, optional, tag = "1")]
    pub branch: ::core::option::Option<crate::lore::model::v1::Branch>,
}
impl ::prost::Name for BranchListResponse {
    const NAME: &'static str = "BranchListResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchListResponse".into()
    }
}
/// Request to push a revision as a branch's new tip.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPushRequest {
    /// Target branch id.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// Content signature of the revision to push. Caller must ensure the
    /// revision and all data it references are present in CAS before
    /// calling.
    #[prost(bytes = "bytes", tag = "2")]
    pub revision_signature: ::prost::bytes::Bytes,
    /// When true, the server replaces the tip directly without checking
    /// whether the new tip descends from the current one. Wins over
    /// `fast_forward_merge` when both are set.
    #[prost(bool, tag = "3")]
    pub force: bool,
    /// When true and the new tip does not descend from the current tip,
    /// the server attempts a fast-forward merge. Mutually superseded by
    /// `force`.
    #[prost(bool, tag = "4")]
    pub fast_forward_merge: bool,
}
impl ::prost::Name for BranchPushRequest {
    const NAME: &'static str = "BranchPushRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchPushRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchPushRequest".into()
    }
}
/// Response describing the resulting branch tip after a push.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPushResponse {
    /// Signature of the resulting tip (may equal the request's
    /// revision_signature, or a new merge revision in the
    /// fast-forward-merge case).
    #[prost(bytes = "bytes", tag = "1")]
    pub revision_signature: ::prost::bytes::Bytes,
    /// Per-branch number of the resulting tip.
    #[prost(uint64, tag = "2")]
    pub revision_number: u64,
    /// True iff the server performed a fast-forward merge to land the
    /// push.
    #[prost(bool, tag = "3")]
    pub fast_forward_merged: bool,
    /// Optional human-readable diagnostic. Free-form; clients should not
    /// parse it.
    #[prost(string, optional, tag = "4")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for BranchPushResponse {
    const NAME: &'static str = "BranchPushResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchPushResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchPushResponse".into()
    }
}
/// Request for a cheap hash-only read of a branch's metadata pointer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataGetRequest {
    /// Branch id.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataGetRequest {
    const NAME: &'static str = "BranchMetadataGetRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchMetadataGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchMetadataGetRequest".into()
    }
}
/// Response carrying the current metadata hash.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataGetResponse {
    /// Current metadata pointer.
    #[prost(bytes = "bytes", tag = "1")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataGetResponse {
    const NAME: &'static str = "BranchMetadataGetResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchMetadataGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchMetadataGetResponse".into()
    }
}
/// Request for a compare-and-swap update of a branch's metadata pointer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataSetRequest {
    /// Branch id.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// The metadata hash the caller expects to be currently set. The
    /// server compares this to the actual current value and only swaps
    /// on match.
    #[prost(bytes = "bytes", tag = "2")]
    pub expected: ::prost::bytes::Bytes,
    /// The metadata hash to install if the CAS succeeds.
    #[prost(bytes = "bytes", tag = "3")]
    pub updated: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataSetRequest {
    const NAME: &'static str = "BranchMetadataSetRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchMetadataSetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchMetadataSetRequest".into()
    }
}
/// Response always returned with gRPC OK regardless of CAS hit or miss.
/// On a successful CAS, response.metadata == request.updated. On a CAS
/// miss, response.metadata reflects the unchanged prior value; the
/// caller compares response.metadata vs request.updated to detect the
/// miss and retry.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchMetadataSetResponse {
    /// The branch's current metadata pointer after the call.
    #[prost(bytes = "bytes", tag = "1")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchMetadataSetResponse {
    const NAME: &'static str = "BranchMetadataSetResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.BranchMetadataSetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.BranchMetadataSetResponse".into()
    }
}
/// Request to page through a branch's revision history. The start
/// anchor selects which revision the page is anchored at; both forms
/// resolve to the same concrete revision and walk that branch's
/// history.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionListRequest {
    /// Start anchor for the page.
    #[prost(oneof = "revision_list_request::Start", tags = "1, 2")]
    pub start: ::core::option::Option<revision_list_request::Start>,
}
/// Nested message and enum types in `RevisionListRequest`.
pub mod revision_list_request {
    /// Start anchor for the page.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Start {
        /// Identifier-based anchor; `number == 0` resolves to the tip of
        /// the branch.
        #[prost(message, tag = "1")]
        Identifier(crate::lore::model::v1::RevisionIdentifier),
        /// Signature-based anchor (typically a cursor returned by a
        /// previous response).
        #[prost(bytes, tag = "2")]
        Signature(::prost::bytes::Bytes),
    }
}
impl ::prost::Name for RevisionListRequest {
    const NAME: &'static str = "RevisionListRequest";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.RevisionListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.RevisionListRequest".into()
    }
}
/// Response carrying a page of revision items (newer-to-older within
/// the page) plus optional cursors for the next pages in either
/// direction.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevisionListResponse {
    /// The page of revisions, newest-to-oldest. The revision identified by
    /// the request's `start` anchor is guaranteed to appear somewhere in
    /// the page, but is not necessarily items\[0\] — the server may align
    /// the page on a wider boundary (e.g. a cached segment) and return
    /// items both newer and older than the anchor. Server picks page size.
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<crate::lore::model::v1::RevisionItem>,
    /// Cursor (signature) to feed back as `start.signature` to fetch
    /// the page of revisions newer than this one. Unset when no further
    /// newer revisions exist.
    #[prost(bytes = "bytes", optional, tag = "2")]
    pub signature_forward: ::core::option::Option<::prost::bytes::Bytes>,
    /// Cursor (signature) to feed back as `start.signature` to fetch
    /// the page of revisions older than this one. Unset when no further
    /// older revisions exist.
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub signature_backward: ::core::option::Option<::prost::bytes::Bytes>,
}
impl ::prost::Name for RevisionListResponse {
    const NAME: &'static str = "RevisionListResponse";
    const PACKAGE: &'static str = "lore.revision.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.revision.v1.RevisionListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.revision.v1.RevisionListResponse".into()
    }
}
/// Generated client implementations.
pub mod revision_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Baseline revision-graph service. Carries the minimal, stable set of
    /// graph primitives — branch lifecycle, metadata CAS, revision listing.
    /// Presentation helpers (describe / tree / diff) live separately on
    /// lore.thin_client.v1.ThinClientService.
    #[derive(Debug, Clone)]
    pub struct RevisionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RevisionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RevisionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RevisionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RevisionServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Create a new branch as a fork of an existing revision chain.
        pub async fn branch_create(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchCreateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.revision.v1.RevisionService", "BranchCreate"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Tombstone a live branch by id. Idempotent on already-tombstoned
        /// branches.
        pub async fn branch_delete(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchDeleteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchDelete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.revision.v1.RevisionService", "BranchDelete"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Look up a branch by id (live or tombstoned) or by name (live only).
        pub async fn branch_get(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.revision.v1.RevisionService", "BranchGet"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream all branches matching the optional filters.
        pub async fn branch_list(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchListRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::BranchListResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.revision.v1.RevisionService", "BranchList"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Set the tip of a branch to a specific revision. Supports force and
        /// fast-forward-merge semantics.
        pub async fn branch_push(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchPushRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchPushResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchPush",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.revision.v1.RevisionService", "BranchPush"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Cheap hash-only read of a branch's current metadata pointer.
        pub async fn branch_metadata_get(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchMetadataGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchMetadataGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchMetadataGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.revision.v1.RevisionService",
                        "BranchMetadataGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Compare-and-swap update of a branch's metadata pointer. CAS miss is
        /// signalled in-band via the response, never as a non-OK gRPC status.
        pub async fn branch_metadata_set(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchMetadataSetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchMetadataSetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/BranchMetadataSet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.revision.v1.RevisionService",
                        "BranchMetadataSet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Page through a branch's revision history. Server picks page size.
        pub async fn revision_list(
            &mut self,
            request: impl tonic::IntoRequest<super::RevisionListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevisionListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.RevisionService/RevisionList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.revision.v1.RevisionService", "RevisionList"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod revision_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RevisionServiceServer.
    #[async_trait]
    pub trait RevisionService: std::marker::Send + std::marker::Sync + 'static {
        /// Create a new branch as a fork of an existing revision chain.
        async fn branch_create(
            &self,
            request: tonic::Request<super::BranchCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchCreateResponse>,
            tonic::Status,
        >;
        /// Tombstone a live branch by id. Idempotent on already-tombstoned
        /// branches.
        async fn branch_delete(
            &self,
            request: tonic::Request<super::BranchDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchDeleteResponse>,
            tonic::Status,
        >;
        /// Look up a branch by id (live or tombstoned) or by name (live only).
        async fn branch_get(
            &self,
            request: tonic::Request<super::BranchGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchGetResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the BranchList method.
        type BranchListStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::BranchListResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream all branches matching the optional filters.
        async fn branch_list(
            &self,
            request: tonic::Request<super::BranchListRequest>,
        ) -> std::result::Result<tonic::Response<Self::BranchListStream>, tonic::Status>;
        /// Set the tip of a branch to a specific revision. Supports force and
        /// fast-forward-merge semantics.
        async fn branch_push(
            &self,
            request: tonic::Request<super::BranchPushRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchPushResponse>,
            tonic::Status,
        >;
        /// Cheap hash-only read of a branch's current metadata pointer.
        async fn branch_metadata_get(
            &self,
            request: tonic::Request<super::BranchMetadataGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchMetadataGetResponse>,
            tonic::Status,
        >;
        /// Compare-and-swap update of a branch's metadata pointer. CAS miss is
        /// signalled in-band via the response, never as a non-OK gRPC status.
        async fn branch_metadata_set(
            &self,
            request: tonic::Request<super::BranchMetadataSetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchMetadataSetResponse>,
            tonic::Status,
        >;
        /// Page through a branch's revision history. Server picks page size.
        async fn revision_list(
            &self,
            request: tonic::Request<super::RevisionListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevisionListResponse>,
            tonic::Status,
        >;
    }
    /// Baseline revision-graph service. Carries the minimal, stable set of
    /// graph primitives — branch lifecycle, metadata CAS, revision listing.
    /// Presentation helpers (describe / tree / diff) live separately on
    /// lore.thin_client.v1.ThinClientService.
    #[derive(Debug)]
    pub struct RevisionServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RevisionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RevisionServiceServer<T>
    where
        T: RevisionService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.revision.v1.RevisionService/BranchCreate" => {
                    #[allow(non_camel_case_types)]
                    struct BranchCreateSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::BranchCreateRequest>
                    for BranchCreateSvc<T> {
                        type Response = super::BranchCreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchCreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchCreateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/BranchDelete" => {
                    #[allow(non_camel_case_types)]
                    struct BranchDeleteSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::BranchDeleteRequest>
                    for BranchDeleteSvc<T> {
                        type Response = super::BranchDeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchDeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_delete(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchDeleteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/BranchGet" => {
                    #[allow(non_camel_case_types)]
                    struct BranchGetSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::BranchGetRequest>
                    for BranchGetSvc<T> {
                        type Response = super::BranchGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/BranchList" => {
                    #[allow(non_camel_case_types)]
                    struct BranchListSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::ServerStreamingService<super::BranchListRequest>
                    for BranchListSvc<T> {
                        type Response = super::BranchListResponse;
                        type ResponseStream = T::BranchListStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/BranchPush" => {
                    #[allow(non_camel_case_types)]
                    struct BranchPushSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::BranchPushRequest>
                    for BranchPushSvc<T> {
                        type Response = super::BranchPushResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchPushRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_push(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchPushSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/BranchMetadataGet" => {
                    #[allow(non_camel_case_types)]
                    struct BranchMetadataGetSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::BranchMetadataGetRequest>
                    for BranchMetadataGetSvc<T> {
                        type Response = super::BranchMetadataGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchMetadataGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_metadata_get(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchMetadataGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/BranchMetadataSet" => {
                    #[allow(non_camel_case_types)]
                    struct BranchMetadataSetSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::BranchMetadataSetRequest>
                    for BranchMetadataSetSvc<T> {
                        type Response = super::BranchMetadataSetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchMetadataSetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::branch_metadata_set(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchMetadataSetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.RevisionService/RevisionList" => {
                    #[allow(non_camel_case_types)]
                    struct RevisionListSvc<T: RevisionService>(pub Arc<T>);
                    impl<
                        T: RevisionService,
                    > tonic::server::UnaryService<super::RevisionListRequest>
                    for RevisionListSvc<T> {
                        type Response = super::RevisionListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevisionListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RevisionService>::revision_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevisionListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RevisionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.revision.v1.RevisionService";
    impl<T> tonic::server::NamedService for RevisionServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated client implementations.
pub mod forwarded_revision_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// A service to receive requests forwarded on from another Lore Sever,
    /// to perform an RPC on behalf of a client
    #[derive(Debug, Clone)]
    pub struct ForwardedRevisionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ForwardedRevisionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ForwardedRevisionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ForwardedRevisionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ForwardedRevisionServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn branch_create(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchCreateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.ForwardedRevisionService/BranchCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.revision.v1.ForwardedRevisionService",
                        "BranchCreate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn branch_delete(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchDeleteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.ForwardedRevisionService/BranchDelete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.revision.v1.ForwardedRevisionService",
                        "BranchDelete",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn branch_get(
            &mut self,
            request: impl tonic::IntoRequest<super::BranchGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.revision.v1.ForwardedRevisionService/BranchGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.revision.v1.ForwardedRevisionService",
                        "BranchGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod forwarded_revision_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ForwardedRevisionServiceServer.
    #[async_trait]
    pub trait ForwardedRevisionService: std::marker::Send + std::marker::Sync + 'static {
        async fn branch_create(
            &self,
            request: tonic::Request<super::BranchCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchCreateResponse>,
            tonic::Status,
        >;
        async fn branch_delete(
            &self,
            request: tonic::Request<super::BranchDeleteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchDeleteResponse>,
            tonic::Status,
        >;
        async fn branch_get(
            &self,
            request: tonic::Request<super::BranchGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BranchGetResponse>,
            tonic::Status,
        >;
    }
    /// A service to receive requests forwarded on from another Lore Sever,
    /// to perform an RPC on behalf of a client
    #[derive(Debug)]
    pub struct ForwardedRevisionServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ForwardedRevisionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for ForwardedRevisionServiceServer<T>
    where
        T: ForwardedRevisionService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.revision.v1.ForwardedRevisionService/BranchCreate" => {
                    #[allow(non_camel_case_types)]
                    struct BranchCreateSvc<T: ForwardedRevisionService>(pub Arc<T>);
                    impl<
                        T: ForwardedRevisionService,
                    > tonic::server::UnaryService<super::BranchCreateRequest>
                    for BranchCreateSvc<T> {
                        type Response = super::BranchCreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchCreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ForwardedRevisionService>::branch_create(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchCreateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.ForwardedRevisionService/BranchDelete" => {
                    #[allow(non_camel_case_types)]
                    struct BranchDeleteSvc<T: ForwardedRevisionService>(pub Arc<T>);
                    impl<
                        T: ForwardedRevisionService,
                    > tonic::server::UnaryService<super::BranchDeleteRequest>
                    for BranchDeleteSvc<T> {
                        type Response = super::BranchDeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchDeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ForwardedRevisionService>::branch_delete(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchDeleteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.revision.v1.ForwardedRevisionService/BranchGet" => {
                    #[allow(non_camel_case_types)]
                    struct BranchGetSvc<T: ForwardedRevisionService>(pub Arc<T>);
                    impl<
                        T: ForwardedRevisionService,
                    > tonic::server::UnaryService<super::BranchGetRequest>
                    for BranchGetSvc<T> {
                        type Response = super::BranchGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BranchGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ForwardedRevisionService>::branch_get(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BranchGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ForwardedRevisionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.revision.v1.ForwardedRevisionService";
    impl<T> tonic::server::NamedService for ForwardedRevisionServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
