// This file is @generated by prost-build.
/// One per-path change in a revision diff. Replaces the old urc Path +
/// PathDiff pair with a single "what happened to this path" entry.
/// In 3-way mode wrapped inside DiffConflict, the change is rooted at the
/// common ancestor.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiffChange {
    /// Destination path (where the entry lives in the "to" side).
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// Source path for MOVE / COPY actions; empty otherwise.
    #[prost(string, tag = "2")]
    pub path_from: ::prost::alloc::string::String,
    /// What kind of change occurred at this path.
    #[prost(enumeration = "Action", tag = "3")]
    pub action: i32,
    /// The kind of node at `path` in the "to" side.
    #[prost(enumeration = "NodeType", tag = "4")]
    pub node_type: i32,
    /// Content address on the "from" side; empty if the action is ADD or
    /// the side has no content here.
    #[prost(bytes = "bytes", tag = "5")]
    pub content_from: ::prost::bytes::Bytes,
    /// Content address on the "to" side; empty if the action is DELETE or
    /// the side has no content here.
    #[prost(bytes = "bytes", tag = "6")]
    pub content_to: ::prost::bytes::Bytes,
    /// True when the server auto-resolved this change in 3-way mode (only
    /// meaningful when the request set `autoresolve = true`).
    #[prost(bool, tag = "7")]
    pub automerged: bool,
    /// Index into the per-stream partition table built from `DiffPartition`
    /// payloads. 0 = the request's repository (the parent partition, never
    /// announced). Non-zero values MUST be preceded on the same stream by
    /// a `DiffPartition` whose `index` matches; the consumer's content
    /// fetch for this change MUST target the corresponding partition,
    /// not the request's repository id.
    #[prost(uint32, tag = "8")]
    pub link_repository_index: u32,
}
impl ::prost::Name for DiffChange {
    const NAME: &'static str = "DiffChange";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.DiffChange".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.DiffChange".into()
    }
}
/// Pair of per-path changes describing a 3-way merge conflict at a single
/// path. Each side's change is rooted at the common ancestor: in particular
/// `change_from.content_from == change_to.content_from` and both equal the
/// resolved base's content address for that path.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiffConflict {
    /// The change one side made relative to the common ancestor.
    #[prost(message, optional, tag = "1")]
    pub change_from: ::core::option::Option<DiffChange>,
    /// The change the other side made relative to the common ancestor.
    #[prost(message, optional, tag = "2")]
    pub change_to: ::core::option::Option<DiffChange>,
}
impl ::prost::Name for DiffConflict {
    const NAME: &'static str = "DiffConflict";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.DiffConflict".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.DiffConflict".into()
    }
}
/// Per-stream partition table entry. Announces a linked partition and
/// the stable index that `DiffChange.link_repository_index` will use to
/// reference it for the remainder of this stream. Server emits each entry
/// at most once, in discovery order starting at index 1, strictly before
/// the first `DiffChange` (or `DiffConflict` half) that references it.
/// Index 0 is reserved for the parent partition and never announced.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiffPartition {
    /// Stable per-stream index. Server assigns 1, 2, 3, … in discovery
    /// order. Never zero.
    #[prost(uint32, tag = "1")]
    pub index: u32,
    /// The partition bytes corresponding to `index` (a Lore `Partition`,
    /// i.e. the repository scope the content of every `DiffChange` with
    /// `link_repository_index == index` resolves under).
    #[prost(bytes = "bytes", tag = "2")]
    pub link_partition: ::prost::bytes::Bytes,
}
impl ::prost::Name for DiffPartition {
    const NAME: &'static str = "DiffPartition";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.DiffPartition".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.DiffPartition".into()
    }
}
/// A single entry in a revision tree listing.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TreeNode {
    /// Repository-relative path of this entry.
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// Whether this entry is a directory, file, or link.
    #[prost(enumeration = "NodeType", tag = "2")]
    pub node_type: i32,
    /// Content address for FILE / LINK entries; unused for DIRECTORY.
    #[prost(message, optional, tag = "3")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
}
impl ::prost::Name for TreeNode {
    const NAME: &'static str = "TreeNode";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.TreeNode".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.TreeNode".into()
    }
}
/// Self-describing revision record. Carries the resolved RevisionIdentifier
/// so callers querying by bare signature learn the resolved (branch, number)
/// in the same response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Revision {
    /// Content signature of this revision. Globally unique; never appears on
    /// two branches.
    #[prost(bytes = "bytes", tag = "1")]
    pub signature: ::prost::bytes::Bytes,
    /// Resolved (branch, number) for this revision. Echoed by the server so
    /// signature-only queries can recover the per-branch coordinates.
    #[prost(message, optional, tag = "2")]
    pub identifier: ::core::option::Option<crate::lore::model::v1::RevisionIdentifier>,
    /// Free-form commit message.
    #[prost(string, tag = "3")]
    pub commit_message: ::prost::alloc::string::String,
    /// Commit timestamp (Unix epoch seconds). Always commit time, never
    /// authorship time.
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    /// Identity that originally created the revision.
    #[prost(string, tag = "5")]
    pub created_by: ::prost::alloc::string::String,
    /// Identity that committed the revision (may differ from created_by).
    #[prost(string, tag = "6")]
    pub committed_by: ::prost::alloc::string::String,
    /// Per-revision metadata entries.
    #[prost(message, repeated, tag = "7")]
    pub metadata: ::prost::alloc::vec::Vec<Metadata>,
    /// Self-side parent (the predecessor on this revision's own branch).
    /// Unset on a branch root; otherwise set.
    #[prost(message, optional, tag = "8")]
    pub parent_self: ::core::option::Option<revision::Parent>,
    /// Other-side parent (only set on merge commits).
    #[prost(message, optional, tag = "9")]
    pub parent_other: ::core::option::Option<revision::Parent>,
    /// Per-branch revision number.
    #[prost(uint64, tag = "10")]
    pub number: u64,
}
/// Nested message and enum types in `Revision`.
pub mod revision {
    /// A parent reference grouping the parent revision's signature and
    /// resolved identifier.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Parent {
        /// Signature of the parent revision.
        #[prost(bytes = "bytes", tag = "1")]
        pub signature: ::prost::bytes::Bytes,
        /// Resolved (branch, number) for the parent revision.
        #[prost(message, optional, tag = "2")]
        pub identifier: ::core::option::Option<
            crate::lore::model::v1::RevisionIdentifier,
        >,
    }
    impl ::prost::Name for Parent {
        const NAME: &'static str = "Parent";
        const PACKAGE: &'static str = "lore.thin_client.v1";
        fn full_name() -> ::prost::alloc::string::String {
            "lore.thin_client.v1.Revision.Parent".into()
        }
        fn type_url() -> ::prost::alloc::string::String {
            "/lore.thin_client.v1.Revision.Parent".into()
        }
    }
}
impl ::prost::Name for Revision {
    const NAME: &'static str = "Revision";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.Revision".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.Revision".into()
    }
}
/// Typed metadata key/value pair associated with a Branch or Revision.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    /// Caller-defined key.
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    /// Encoded value; interpretation depends on `metadata_type`.
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    /// Type tag indicating how `value` should be parsed.
    #[prost(enumeration = "MetadataType", tag = "3")]
    pub metadata_type: i32,
}
impl ::prost::Name for Metadata {
    const NAME: &'static str = "Metadata";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.Metadata".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.Metadata".into()
    }
}
/// File-content diff request. ContentDiff is server-streaming and operates
/// purely on CAS addresses — no path field, no per-revision context.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContentDiffRequest {
    /// Content address of the "from" side. Empty bytes represent
    /// "no content" (e.g. file added).
    #[prost(bytes = "bytes", tag = "1")]
    pub address_from: ::prost::bytes::Bytes,
    /// Content address of the "to" side. Empty bytes represent
    /// "no content" (e.g. file deleted).
    #[prost(bytes = "bytes", tag = "2")]
    pub address_to: ::prost::bytes::Bytes,
    /// Common ancestor's content address. Presence (set, non-empty)
    /// triggers 3-way merge mode; absence gives 2-way unified diff. There
    /// is no separate mode flag.
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub address_base: ::core::option::Option<::prost::bytes::Bytes>,
    /// Number of context lines around each hunk in the unified diff
    /// output. Server picks a default if unset.
    #[prost(uint32, optional, tag = "4")]
    pub context_lines: ::core::option::Option<u32>,
    /// When true, lines that differ only in trailing whitespace are
    /// treated as equal for stat / change-detection purposes. The
    /// displayed diff text uses original (un-normalised) content.
    #[prost(bool, tag = "5")]
    pub ignore_whitespace_eol: bool,
    /// When true, runs of internal whitespace are collapsed to a single
    /// space before comparing for stat / change-detection purposes.
    #[prost(bool, tag = "6")]
    pub ignore_whitespace_inline: bool,
    /// Maximum size in bytes of the generated diff text. When exceeded,
    /// the response header sets `truncated = true` and emits no chunks;
    /// summary stats are still computed.
    #[prost(uint64, optional, tag = "7")]
    pub max_diff_size: ::core::option::Option<u64>,
}
impl ::prost::Name for ContentDiffRequest {
    const NAME: &'static str = "ContentDiffRequest";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.ContentDiffRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.ContentDiffRequest".into()
    }
}
/// Server-streamed response for ContentDiff. The first message MUST carry
/// `payload.header`; subsequent messages carry `payload.chunk`. Server MUST
/// NOT emit a ContentDiffResponse with `payload` unset.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContentDiffResponse {
    #[prost(oneof = "content_diff_response::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<content_diff_response::Payload>,
}
/// Nested message and enum types in `ContentDiffResponse`.
pub mod content_diff_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        /// Summary stats and mode flags, computed up-front and emitted first.
        #[prost(message, tag = "1")]
        Header(super::ContentDiffHeader),
        /// A chunk of diff text. Concatenating `chunk.diff` strings in
        /// arrival order reproduces the full diff text.
        #[prost(message, tag = "2")]
        Chunk(super::ContentDiffChunkResponse),
    }
}
impl ::prost::Name for ContentDiffResponse {
    const NAME: &'static str = "ContentDiffResponse";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.ContentDiffResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.ContentDiffResponse".into()
    }
}
/// Header for a ContentDiff stream. Reports summary stats and short-circuit
/// flags that may end the stream after the header.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContentDiffHeader {
    /// Number of lines added (after any whitespace preprocessing).
    #[prost(uint64, tag = "1")]
    pub lines_added: u64,
    /// Number of lines deleted (after any whitespace preprocessing).
    #[prost(uint64, tag = "2")]
    pub lines_deleted: u64,
    /// True when the input is detected as binary; the stream emits no
    /// chunks and stats are zero.
    #[prost(bool, tag = "3")]
    pub binary: bool,
    /// True when the generated diff would exceed `max_diff_size`; the
    /// stream emits no chunks but stats are still reported.
    #[prost(bool, tag = "4")]
    pub truncated: bool,
    /// True only in 3-way mode when the merge produced conflict markers.
    #[prost(bool, tag = "5")]
    pub has_conflicts: bool,
    /// Number of conflict regions in the merged text (3-way only).
    #[prost(uint32, tag = "6")]
    pub conflict_count: u32,
}
impl ::prost::Name for ContentDiffHeader {
    const NAME: &'static str = "ContentDiffHeader";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.ContentDiffHeader".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.ContentDiffHeader".into()
    }
}
/// A single chunk of diff text. Server picks chunk boundaries on UTF-8
/// character boundaries; clients MUST NOT assume line alignment. Reserved
/// for future additive fields (hunk index, byte offsets, etc.) under
/// proto3 append-only rules.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContentDiffChunkResponse {
    /// Diff text for this chunk.
    #[prost(string, tag = "1")]
    pub diff: ::prost::alloc::string::String,
}
impl ::prost::Name for ContentDiffChunkResponse {
    const NAME: &'static str = "ContentDiffChunkResponse";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.ContentDiffChunkResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.ContentDiffChunkResponse".into()
    }
}
/// File-system entry kind for tree listings and diff entries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeType {
    /// A directory.
    Directory = 0,
    /// A regular file.
    File = 1,
    /// A symbolic link.
    Link = 2,
}
impl NodeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Directory => "DIRECTORY",
            Self::File => "FILE",
            Self::Link => "LINK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECTORY" => Some(Self::Directory),
            "FILE" => Some(Self::File),
            "LINK" => Some(Self::Link),
            _ => None,
        }
    }
}
/// Per-path action describing what happened between two states (or relative
/// to the common ancestor in 3-way merges).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Action {
    /// No change at this path.
    Keep = 0,
    /// The path was added.
    Add = 1,
    /// The path was removed.
    Delete = 2,
    /// The path was moved (rename + parent change).
    Move = 3,
    /// The path was copied to a new location.
    Copy = 4,
}
impl Action {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Keep => "KEEP",
            Self::Add => "ADD",
            Self::Delete => "DELETE",
            Self::Move => "MOVE",
            Self::Copy => "COPY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "KEEP" => Some(Self::Keep),
            "ADD" => Some(Self::Add),
            "DELETE" => Some(Self::Delete),
            "MOVE" => Some(Self::Move),
            "COPY" => Some(Self::Copy),
            _ => None,
        }
    }
}
/// Type tag for a Metadata value, mirroring the corresponding urc enum.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MetadataType {
    /// Address bytes (content reference).
    Address = 0,
    /// Boolean value encoded as "true" / "false" string.
    Boolean = 1,
    /// Opaque binary value.
    Binary = 2,
    /// Addressing context bytes.
    Context = 3,
    /// Hash bytes.
    Hash = 4,
    /// Numeric value encoded as a string.
    Numeric = 5,
    /// UTF-8 string value.
    String = 6,
}
impl MetadataType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Address => "ADDRESS",
            Self::Boolean => "BOOLEAN",
            Self::Binary => "BINARY",
            Self::Context => "CONTEXT",
            Self::Hash => "HASH",
            Self::Numeric => "NUMERIC",
            Self::String => "STRING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ADDRESS" => Some(Self::Address),
            "BOOLEAN" => Some(Self::Boolean),
            "BINARY" => Some(Self::Binary),
            "CONTEXT" => Some(Self::Context),
            "HASH" => Some(Self::Hash),
            "NUMERIC" => Some(Self::Numeric),
            "STRING" => Some(Self::String),
            _ => None,
        }
    }
}
/// Request to describe a single revision by identifier or signature.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionInfoRequest {
    #[prost(oneof = "revision_info_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<revision_info_request::Query>,
}
/// Nested message and enum types in `RevisionInfoRequest`.
pub mod revision_info_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// Identifier-based lookup; `number == 0` resolves to the tip of
        /// the branch.
        #[prost(message, tag = "1")]
        Identifier(crate::lore::model::v1::RevisionIdentifier),
        /// Signature-based lookup.
        #[prost(bytes, tag = "2")]
        Signature(::prost::bytes::Bytes),
    }
}
impl ::prost::Name for RevisionInfoRequest {
    const NAME: &'static str = "RevisionInfoRequest";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionInfoRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionInfoRequest".into()
    }
}
/// Response carrying the resolved Revision record. Self-describing —
/// includes the resolved RevisionIdentifier even when queried by
/// signature.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevisionInfoResponse {
    /// The full Revision record.
    #[prost(message, optional, tag = "1")]
    pub revision: ::core::option::Option<Revision>,
}
impl ::prost::Name for RevisionInfoResponse {
    const NAME: &'static str = "RevisionInfoResponse";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionInfoResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionInfoResponse".into()
    }
}
/// Request to diff two revisions. Server picks the diff mode (2-way vs
/// 3-way) from revision metadata; callers do not declare it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionDiffRequest {
    /// When true and the server picks 3-way mode, auto-resolved
    /// DiffChange entries are flagged via `automerged = true`. Silently
    /// ignored in 2-way mode.
    #[prost(bool, tag = "5")]
    pub autoresolve: bool,
    /// "From" side specifier.
    #[prost(oneof = "revision_diff_request::QueryFrom", tags = "1, 2")]
    pub query_from: ::core::option::Option<revision_diff_request::QueryFrom>,
    /// "To" side specifier.
    #[prost(oneof = "revision_diff_request::QueryTo", tags = "3, 4")]
    pub query_to: ::core::option::Option<revision_diff_request::QueryTo>,
}
/// Nested message and enum types in `RevisionDiffRequest`.
pub mod revision_diff_request {
    /// "From" side specifier.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum QueryFrom {
        /// Identifier-based "from" (`number == 0` = tip).
        #[prost(message, tag = "1")]
        IdentifierFrom(crate::lore::model::v1::RevisionIdentifier),
        /// Signature-based "from".
        #[prost(bytes, tag = "2")]
        SignatureFrom(::prost::bytes::Bytes),
    }
    /// "To" side specifier.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum QueryTo {
        /// Identifier-based "to" (`number == 0` = tip).
        #[prost(message, tag = "3")]
        IdentifierTo(crate::lore::model::v1::RevisionIdentifier),
        /// Signature-based "to".
        #[prost(bytes, tag = "4")]
        SignatureTo(::prost::bytes::Bytes),
    }
}
impl ::prost::Name for RevisionDiffRequest {
    const NAME: &'static str = "RevisionDiffRequest";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionDiffRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionDiffRequest".into()
    }
}
/// Header for a RevisionDiff stream. Echoes the resolved revisions so
/// callers querying by signature learn the (branch, number) and vice
/// versa. Optional `_base` fields are populated only when the server
/// selected a 3-way diff.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionDiffHeader {
    /// Resolved (branch, number) of the "from" side.
    #[prost(message, optional, tag = "1")]
    pub identifier_from: ::core::option::Option<
        crate::lore::model::v1::RevisionIdentifier,
    >,
    /// Resolved signature of the "from" side.
    #[prost(bytes = "bytes", tag = "2")]
    pub signature_from: ::prost::bytes::Bytes,
    /// Resolved (branch, number) of the "to" side.
    #[prost(message, optional, tag = "3")]
    pub identifier_to: ::core::option::Option<
        crate::lore::model::v1::RevisionIdentifier,
    >,
    /// Resolved signature of the "to" side.
    #[prost(bytes = "bytes", tag = "4")]
    pub signature_to: ::prost::bytes::Bytes,
    /// Resolved (branch, number) of the common ancestor base. Set only
    /// in 3-way mode.
    #[prost(message, optional, tag = "5")]
    pub identifier_base: ::core::option::Option<
        crate::lore::model::v1::RevisionIdentifier,
    >,
    /// Resolved signature of the common ancestor base. Set only in
    /// 3-way mode.
    #[prost(bytes = "bytes", optional, tag = "6")]
    pub signature_base: ::core::option::Option<::prost::bytes::Bytes>,
}
impl ::prost::Name for RevisionDiffHeader {
    const NAME: &'static str = "RevisionDiffHeader";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionDiffHeader".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionDiffHeader".into()
    }
}
/// Server-streamed response for RevisionDiff. First message carries
/// `payload.header`; subsequent messages stream `DiffChange` always,
/// `DiffConflict` only in 3-way mode, and `DiffPartition` lazily as the
/// server discovers linked repositories during the walk. Each
/// `DiffPartition` is emitted strictly before the first `DiffChange` or
/// `DiffConflict` half that references its index.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionDiffResponse {
    #[prost(oneof = "revision_diff_response::Payload", tags = "1, 2, 3, 4")]
    pub payload: ::core::option::Option<revision_diff_response::Payload>,
}
/// Nested message and enum types in `RevisionDiffResponse`.
pub mod revision_diff_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        /// Header echoing the resolved revisions.
        #[prost(message, tag = "1")]
        Header(super::RevisionDiffHeader),
        /// A per-path change.
        #[prost(message, tag = "2")]
        Change(super::DiffChange),
        /// A 3-way merge conflict pair (3-way mode only).
        #[prost(message, tag = "3")]
        Conflict(super::DiffConflict),
        /// A linked-repository announcement.
        #[prost(message, tag = "4")]
        Partition(super::DiffPartition),
    }
}
impl ::prost::Name for RevisionDiffResponse {
    const NAME: &'static str = "RevisionDiffResponse";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionDiffResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionDiffResponse".into()
    }
}
/// Request to walk the file/directory tree at a specific revision.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionTreeRequest {
    /// If set and non-empty, only entries at or under this path are
    /// emitted. The prefix itself is emitted as a DIRECTORY node when
    /// it exists. If unset or empty, the walk covers the full tree from
    /// the repository root.
    #[prost(string, optional, tag = "3")]
    pub path_prefix: ::core::option::Option<::prost::alloc::string::String>,
    /// If set, limits the depth of descent below the prefix root. 1
    /// emits only direct children of the prefix root; 2 emits direct
    /// children plus grandchildren; etc. 0 or unset means unbounded.
    #[prost(uint32, optional, tag = "4")]
    pub max_depth: ::core::option::Option<u32>,
    /// Revision specifier.
    #[prost(oneof = "revision_tree_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<revision_tree_request::Query>,
}
/// Nested message and enum types in `RevisionTreeRequest`.
pub mod revision_tree_request {
    /// Revision specifier.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// Identifier-based lookup; `number == 0` resolves to the tip of
        /// the branch.
        #[prost(message, tag = "1")]
        Identifier(crate::lore::model::v1::RevisionIdentifier),
        /// Signature-based lookup.
        #[prost(bytes, tag = "2")]
        Signature(::prost::bytes::Bytes),
    }
}
impl ::prost::Name for RevisionTreeRequest {
    const NAME: &'static str = "RevisionTreeRequest";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionTreeRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionTreeRequest".into()
    }
}
/// Header for a RevisionTree stream. Echoes the resolved revision so
/// callers querying by signature learn the (branch, number) and vice
/// versa.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionTreeHeader {
    /// Resolved (branch, number) of the revision being walked.
    #[prost(message, optional, tag = "1")]
    pub identifier: ::core::option::Option<crate::lore::model::v1::RevisionIdentifier>,
    /// Resolved signature of the revision being walked.
    #[prost(bytes = "bytes", tag = "2")]
    pub signature: ::prost::bytes::Bytes,
}
impl ::prost::Name for RevisionTreeHeader {
    const NAME: &'static str = "RevisionTreeHeader";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionTreeHeader".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionTreeHeader".into()
    }
}
/// Server-streamed response for RevisionTree. First message carries
/// `payload.header`; subsequent messages stream `TreeNode` items in
/// server-natural order.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionTreeResponse {
    #[prost(oneof = "revision_tree_response::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<revision_tree_response::Payload>,
}
/// Nested message and enum types in `RevisionTreeResponse`.
pub mod revision_tree_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        /// Header echoing the resolved revision.
        #[prost(message, tag = "1")]
        Header(super::RevisionTreeHeader),
        /// A tree entry (directory, file, or link).
        #[prost(message, tag = "2")]
        Node(super::TreeNode),
    }
}
impl ::prost::Name for RevisionTreeResponse {
    const NAME: &'static str = "RevisionTreeResponse";
    const PACKAGE: &'static str = "lore.thin_client.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.thin_client.v1.RevisionTreeResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.thin_client.v1.RevisionTreeResponse".into()
    }
}
/// Generated client implementations.
pub mod thin_client_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Thin-client presentation helpers — describe / tree / diff RPCs that are
    /// convenience helpers for clients that lack local cache or compute ( web UIs).
    /// Sits alongside the baseline lore.revision.v1.RevisionService and shares the
    /// same backing revision-graph state.
    #[derive(Debug, Clone)]
    pub struct ThinClientServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ThinClientServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ThinClientServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ThinClientServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ThinClientServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stream a unified diff or 3-way merge of two CAS blobs as header +
        /// chunked text.
        pub async fn content_diff(
            &mut self,
            request: impl tonic::IntoRequest<super::ContentDiffRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ContentDiffResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.thin_client.v1.ThinClientService/ContentDiff",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.thin_client.v1.ThinClientService",
                        "ContentDiff",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Return the full Revision record for a specific revision.
        pub async fn revision_info(
            &mut self,
            request: impl tonic::IntoRequest<super::RevisionInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevisionInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.thin_client.v1.ThinClientService/RevisionInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.thin_client.v1.ThinClientService",
                        "RevisionInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream a unified 2-way / 3-way diff between two revisions as
        /// header + DiffChange / DiffConflict items.
        pub async fn revision_diff(
            &mut self,
            request: impl tonic::IntoRequest<super::RevisionDiffRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RevisionDiffResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.thin_client.v1.ThinClientService/RevisionDiff",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.thin_client.v1.ThinClientService",
                        "RevisionDiff",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream the file/directory tree at a revision as header + TreeNode
        /// items.
        pub async fn revision_tree(
            &mut self,
            request: impl tonic::IntoRequest<super::RevisionTreeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RevisionTreeResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.thin_client.v1.ThinClientService/RevisionTree",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.thin_client.v1.ThinClientService",
                        "RevisionTree",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod thin_client_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ThinClientServiceServer.
    #[async_trait]
    pub trait ThinClientService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the ContentDiff method.
        type ContentDiffStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ContentDiffResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream a unified diff or 3-way merge of two CAS blobs as header +
        /// chunked text.
        async fn content_diff(
            &self,
            request: tonic::Request<super::ContentDiffRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ContentDiffStream>,
            tonic::Status,
        >;
        /// Return the full Revision record for a specific revision.
        async fn revision_info(
            &self,
            request: tonic::Request<super::RevisionInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevisionInfoResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the RevisionDiff method.
        type RevisionDiffStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RevisionDiffResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream a unified 2-way / 3-way diff between two revisions as
        /// header + DiffChange / DiffConflict items.
        async fn revision_diff(
            &self,
            request: tonic::Request<super::RevisionDiffRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::RevisionDiffStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the RevisionTree method.
        type RevisionTreeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RevisionTreeResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream the file/directory tree at a revision as header + TreeNode
        /// items.
        async fn revision_tree(
            &self,
            request: tonic::Request<super::RevisionTreeRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::RevisionTreeStream>,
            tonic::Status,
        >;
    }
    /// Thin-client presentation helpers — describe / tree / diff RPCs that are
    /// convenience helpers for clients that lack local cache or compute ( web UIs).
    /// Sits alongside the baseline lore.revision.v1.RevisionService and shares the
    /// same backing revision-graph state.
    #[derive(Debug)]
    pub struct ThinClientServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ThinClientServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ThinClientServiceServer<T>
    where
        T: ThinClientService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.thin_client.v1.ThinClientService/ContentDiff" => {
                    #[allow(non_camel_case_types)]
                    struct ContentDiffSvc<T: ThinClientService>(pub Arc<T>);
                    impl<
                        T: ThinClientService,
                    > tonic::server::ServerStreamingService<super::ContentDiffRequest>
                    for ContentDiffSvc<T> {
                        type Response = super::ContentDiffResponse;
                        type ResponseStream = T::ContentDiffStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ContentDiffRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ThinClientService>::content_diff(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ContentDiffSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.thin_client.v1.ThinClientService/RevisionInfo" => {
                    #[allow(non_camel_case_types)]
                    struct RevisionInfoSvc<T: ThinClientService>(pub Arc<T>);
                    impl<
                        T: ThinClientService,
                    > tonic::server::UnaryService<super::RevisionInfoRequest>
                    for RevisionInfoSvc<T> {
                        type Response = super::RevisionInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevisionInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ThinClientService>::revision_info(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevisionInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.thin_client.v1.ThinClientService/RevisionDiff" => {
                    #[allow(non_camel_case_types)]
                    struct RevisionDiffSvc<T: ThinClientService>(pub Arc<T>);
                    impl<
                        T: ThinClientService,
                    > tonic::server::ServerStreamingService<super::RevisionDiffRequest>
                    for RevisionDiffSvc<T> {
                        type Response = super::RevisionDiffResponse;
                        type ResponseStream = T::RevisionDiffStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevisionDiffRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ThinClientService>::revision_diff(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevisionDiffSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.thin_client.v1.ThinClientService/RevisionTree" => {
                    #[allow(non_camel_case_types)]
                    struct RevisionTreeSvc<T: ThinClientService>(pub Arc<T>);
                    impl<
                        T: ThinClientService,
                    > tonic::server::ServerStreamingService<super::RevisionTreeRequest>
                    for RevisionTreeSvc<T> {
                        type Response = super::RevisionTreeResponse;
                        type ResponseStream = T::RevisionTreeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevisionTreeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ThinClientService>::revision_tree(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevisionTreeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ThinClientServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.thin_client.v1.ThinClientService";
    impl<T> tonic::server::NamedService for ThinClientServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
