// This file is @generated by prost-build.
/// Storage fragment header — describes a unit of content-addressed payload
/// returned from the storage layer.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Fragment {
    /// Implementation-defined fragment flags (compression, encryption, etc.).
    #[prost(uint32, tag = "1")]
    pub flags: u32,
    /// Wire size of the fragment payload after any encoding (compressed bytes).
    #[prost(uint32, tag = "2")]
    pub size_payload: u32,
    /// Logical size of the underlying content before encoding.
    #[prost(uint64, tag = "3")]
    pub size_content: u64,
}
impl ::prost::Name for Fragment {
    const NAME: &'static str = "Fragment";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.Fragment".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.Fragment".into()
    }
}
/// Content-addressed handle for a stored object.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    /// Content hash uniquely identifying the object.
    #[prost(bytes = "bytes", tag = "1")]
    pub hash: ::prost::bytes::Bytes,
    /// Optional addressing context (e.g. partition / namespace tag).
    #[prost(bytes = "bytes", tag = "2")]
    pub context: ::prost::bytes::Bytes,
}
impl ::prost::Name for Address {
    const NAME: &'static str = "Address";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.Address".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.Address".into()
    }
}
/// Anchor identifying a specific revision on a specific branch by content
/// signature. Used in Branch.stack (ancestry chain) and in any context where
/// the revision must be concrete (e.g. BranchCreate's caller-supplied stack).
/// Carries the signature only; callers needing the per-branch revision number
/// look it up via RevisionInfo.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BranchPoint {
    /// Branch the parent revision lives on.
    #[prost(bytes = "bytes", tag = "1")]
    pub branch_id: ::prost::bytes::Bytes,
    /// Content signature of the parent revision.
    #[prost(bytes = "bytes", tag = "2")]
    pub revision_signature: ::prost::bytes::Bytes,
}
impl ::prost::Name for BranchPoint {
    const NAME: &'static str = "BranchPoint";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.BranchPoint".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.BranchPoint".into()
    }
}
/// Request-time specifier for a revision. RevisionIdentifier is paired with
/// `bytes signature` in oneof `query` / `query_<side>` / `start` fields per
/// the unified revision-specifier convention.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionIdentifier {
    /// Branch the revision lives on.
    #[prost(bytes = "bytes", tag = "1")]
    pub branch_id: ::prost::bytes::Bytes,
    /// Per-branch revision number. In any v1 *request*, value 0 resolves to
    /// the current tip of the branch; the server resolves 0 to a concrete
    /// number at request time. Valid Storage and response state always carry
    /// concrete numbers; 0 never appears there.
    /// Exception: BranchCreate requires fully-resolved concrete signatures via BranchPoint stack.
    /// Exception: In responses, zeroed revision signatures resolve to a zeroed revision number
    #[prost(uint64, tag = "2")]
    pub number: u64,
}
impl ::prost::Name for RevisionIdentifier {
    const NAME: &'static str = "RevisionIdentifier";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.RevisionIdentifier".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.RevisionIdentifier".into()
    }
}
/// Lean projection of a revision used in list responses (e.g.
/// RevisionListResponse.items). Carries enough to identify the revision
/// and present a list-row entry without the full Revision payload.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevisionItem {
    /// Revision number on its branch.
    #[prost(uint64, tag = "1")]
    pub number: u64,
    /// Content signature of the revision.
    #[prost(bytes = "bytes", tag = "2")]
    pub signature: ::prost::bytes::Bytes,
    /// Metadata hash associated with this revision.
    #[prost(bytes = "bytes", tag = "3")]
    pub metadata: ::prost::bytes::Bytes,
    /// Serialized state header.
    #[prost(bytes = "bytes", tag = "4")]
    pub state: ::prost::bytes::Bytes,
}
impl ::prost::Name for RevisionItem {
    const NAME: &'static str = "RevisionItem";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.RevisionItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.RevisionItem".into()
    }
}
/// A repository — the top-level container for a revision graph. Repositories
/// are hard-deleted (no `deleted` flag): a deleted repository disappears
/// from RepositoryGet / RepositoryList entirely and its name becomes free
/// for reuse.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Repository {
    /// Server-assigned unique identifier; stable across renames.
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// Human-readable name. Unique among live repositories. Validation rules
    /// are defined by lore-revision (see `repository::is_valid_name`).
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Free-form caller-supplied description.
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// Default branch id, fixed at create time and stored in the repository
    /// metadata blob.
    #[prost(bytes = "bytes", tag = "4")]
    pub default_branch_id: ::prost::bytes::Bytes,
    /// Default branch name, fixed at create time.
    #[prost(string, tag = "5")]
    pub default_branch_name: ::prost::alloc::string::String,
    /// Identity that created the repository (caller-supplied when permitted,
    /// else the authenticated JWT identity).
    #[prost(string, tag = "6")]
    pub creator: ::prost::alloc::string::String,
    /// Server-assigned creation timestamp (Unix epoch seconds).
    #[prost(uint64, tag = "7")]
    pub created: u64,
    /// Current metadata pointer hash; mutated atomically via
    /// RepositoryMetadataSet.
    #[prost(bytes = "bytes", tag = "8")]
    pub metadata: ::prost::bytes::Bytes,
}
impl ::prost::Name for Repository {
    const NAME: &'static str = "Repository";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.Repository".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.Repository".into()
    }
}
/// A branch in the revision graph. Tombstoned (deleted=true) branches are
/// preserved by id but their name → id mapping is erased per the
/// "Branch names are exclusive to live branches" invariant.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Branch {
    /// Server-assigned unique identifier; stable across renames and
    /// deletion (tombstone preserves id).
    #[prost(bytes = "bytes", tag = "1")]
    pub id: ::prost::bytes::Bytes,
    /// Human-readable name. Unique among live branches; freed for reuse on
    /// BranchDelete. Validation rules are defined by lore-revision.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Identity that created the branch (caller-supplied when permitted, else
    /// the authenticated JWT identity).
    #[prost(string, tag = "3")]
    pub creator: ::prost::alloc::string::String,
    /// Free-form caller-defined tag for grouping or filtering branches by
    /// intent. Server stores verbatim; no enforced vocabulary.
    #[prost(string, tag = "4")]
    pub category: ::prost::alloc::string::String,
    /// Server-assigned creation timestamp (Unix epoch seconds).
    #[prost(uint64, tag = "5")]
    pub created: u64,
    /// Signature of the current branch tip.
    #[prost(bytes = "bytes", tag = "6")]
    pub latest: ::prost::bytes::Bytes,
    /// True iff the branch has been tombstoned via BranchDelete. The record
    /// survives but the name → id lookup is erased.
    #[prost(bool, tag = "7")]
    pub deleted: bool,
    /// Current metadata hash; mutated atomically via BranchMetadataSet.
    #[prost(bytes = "bytes", tag = "8")]
    pub metadata: ::prost::bytes::Bytes,
    /// Ancestry chain — parent-first, root-last. stack\[0\] is the immediate
    /// parent the branch was forked from; stack\[N-1\] is the ultimate root.
    #[prost(message, repeated, tag = "9")]
    pub stack: ::prost::alloc::vec::Vec<BranchPoint>,
}
impl ::prost::Name for Branch {
    const NAME: &'static str = "Branch";
    const PACKAGE: &'static str = "lore.model.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.model.v1.Branch".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.model.v1.Branch".into()
    }
}
/// Result of a fragment lookup against the storage layer.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FragmentState {
    /// Found in the caller-supplied addressing context.
    FoundInContext = 0,
    /// Found, but in a different context than the caller supplied.
    Found = 1,
    /// No fragment exists at this address in any reachable context.
    NotFound = 2,
    /// Lookup failed for an indeterminate reason.
    Unknown = 3,
}
impl FragmentState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FoundInContext => "FOUND_IN_CONTEXT",
            Self::Found => "FOUND",
            Self::NotFound => "NOT_FOUND",
            Self::Unknown => "UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FOUND_IN_CONTEXT" => Some(Self::FoundInContext),
            "FOUND" => Some(Self::Found),
            "NOT_FOUND" => Some(Self::NotFound),
            "UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
