// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT
//! # urc-error-set
//!
//! Composable, traceable error handling for Rust.
//!
//! This library provides:
//!
//! - **Error sets** via the `#[error_set]` attribute macro — compose discrete
//!   error types into named enums with automatic `From` implementations and
//!   runtime cross-set mapping.
//!
//! - **`Internal`** — a catch-all error type that preserves the original error
//!   as its source, with optional context strings.
//!
//! - **`Traced<E>`** — a wrapper that pairs errors with source location traces
//!   (feature-gated via `track-locations`).
//!
//! - **`ResultExt`** — extension trait on `Result` providing `.try_match()`
//!   and `.map_matched_err()` for ergonomic error mapping with mandatory
//!   context. Propagation uses the per-source-set strict `.forward()`
//!   generated by `#[error_set]`, which requires the target to declare every
//!   variant of the source at compile time.
//!
//! - **`FfiError`** — trait for errors carrying FFI-compatible integer codes.
//!
//! ## Feature Flags
//!
//! - **`track-locations`** (disabled by default): Enables source location
//!   capture in traces. When disabled, all tracing types are zero-sized.
//!
//! ## Quick Start
//!
//! ```
//! use lore_error_set::prelude::*;
//! use std::fmt;
//!
//! // Define discrete error types first. Discrete types must be `pub` so the
//! // generated `type Variants` on the `ErrorSet` impl can name them.
//! #[derive(Debug, Clone)]
//! pub struct NotFound { pub resource: String }
//! impl fmt::Display for NotFound {
//!     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
//!         write!(f, "not found: {}", self.resource)
//!     }
//! }
//! impl std::error::Error for NotFound {}
//! impl FfiError for NotFound { fn ffi_code(&self) -> i32 { 1 } }
//!
//! #[derive(Debug, Clone)]
//! pub struct Timeout;
//! impl fmt::Display for Timeout {
//!     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { write!(f, "timeout") }
//! }
//! impl std::error::Error for Timeout {}
//! impl FfiError for Timeout { fn ffi_code(&self) -> i32 { 2 } }
//!
//! #[error_set]
//! pub enum MyErrors {
//!     NotFound,
//!     Timeout,
//! }
//!
//! // The generated enum has 3 variants: NotFound, Timeout, and Internal.
//! let err: MyErrors = NotFound { resource: "doc".into() }.into();
//! assert!(err.is_not_found());
//! ```

pub mod ext;
pub mod ffi;
pub mod internal;
pub mod location;
pub mod set;
pub mod traced;

// Re-export the proc-macros.
pub use lore_error_set_macro::error_set;
pub use lore_error_set_macro::FfiError;

// Re-export core types at crate root for convenience.
pub use crate::ext::{ForwardStrict, ResultExt, WrapInternal};
pub use crate::ffi::FfiError;
pub use crate::internal::Internal;
pub use crate::location::Location;
pub use crate::set::variants;
pub use crate::set::ErrorSet;
pub use crate::set::Has;
pub use crate::set::HasAll;
pub use crate::set::TracedBox;
pub use crate::traced::ChainError;
pub use crate::traced::HasTrace;
pub use crate::traced::Trace;
pub use crate::traced::Traced;
pub use crate::traced::MAX_TRACE_DEPTH;

/// Prelude module for convenient glob imports.
///
/// ```
/// use lore_error_set::prelude::*;
/// ```
///
/// This re-exports the most commonly used types and traits:
/// - [`error_set`] — the attribute macro (placeholder, implemented in TASK-002)
/// - [`ResultExt`] — extension trait on `Result`
/// - [`ErrorSet`] — core trait for error sets
/// - [`FfiError`] — FFI error code trait
/// - [`Traced`] — error trace wrapper
/// - [`Internal`] — catch-all internal error type
pub mod prelude {
    pub use lore_error_set_macro::error_set;
    pub use lore_error_set_macro::FfiError;

    pub use crate::ext::ForwardStrict;
    pub use crate::ext::ResultExt;
    pub use crate::ext::WrapInternal;
    pub use crate::ffi::FfiError;
    pub use crate::internal::Internal;
    pub use crate::set::ErrorSet;
    pub use crate::set::Has;
    pub use crate::traced::ChainError;
    pub use crate::traced::HasTrace;
    pub use crate::traced::Traced;
}
